[project]
name = "starting-codebase"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chromadb==1.0.15",
    "sentence-transformers==5.0.0",
    "langchain-community==0.2.10",
    "langchain-core==0.2.23",
    "langchain-openai==0.1.14",
    "fastapi==0.116.1",
    "uvicorn==0.35.0",
    "python-multipart==0.0.20",
    "python-dotenv==1.1.1",
    "pytest==8.3.2",
    "pytest-mock==3.14.0",
    "black==24.4.2",
    "isort==5.13.2",
    "ruff==0.5.5",
]

<<<<<<< HEAD
[tool.ruff]
line-length = 88

[tool.ruff.lint]
extend-select = ["I"]

[tool.pytest.ini_options]
testpaths = [
    "backend/tests",
]
python_files = "test_*.py"

